<?php

function get_ship_list() {
    $shiplist = array();
    $result = db_query("SELECT * FROM node WHERE type = 'expansion'")->fetchCol();
    foreach($result as $shipname)
    {
        $nodeid = node_load($shipname);
        $title = $nodeid->title;
        $image = field_get_items('node',$nodeid,'field_ship_image');
        $image = $image[0]['filename'];
        $shiplist[$image] = $title;
    }
    // echo '<pre>';
    // print_r($shiplist);
    // echo '</pre>';
    // exit;

    return $shiplist;
}

function compare_ships_menu() {
    $items['compare_ships'] = array(
        'title' => 'Compare Ships',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('compare_ships_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['compare_ships_results'] = array(
        'title' => 'Ships',
        'page callback' => 'compare_ships_results',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function compare_ships_form() {
    $form['ship1'] = array(
        '#title' => 'Ship 1',
        '#type' => 'select',
        '#description' => 'please choose a ship to compare',
        '#options' => $shipChoices = get_ship_list(),
    );
    $form['ship2'] = array(
        '#title' => 'Ship 1',
        '#type' => 'select',
        '#description' => 'please choose a ship to compare',
        '#options' => $shipChoices = get_ship_list(),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'submit',
    );

    if (!empty($form_state['values']['ship1'])) {
        $form['replace_ship_card']['#description'] = t('testing 123');
    }
    return $form;
}

function compare_ships_form_submit($form, &$form_state) {
    $_SESSION['ship image1'] = $form_state['values']['ship1'];
    $_SESSION['ship image2'] = $form_state['values']['ship2'];
    $form_state['redirect'] = 'compare_ships_results';
}

function compare_ships_results()
{
    $src1 = 'sites/default/files/' . $_SESSION['ship image1'];
    $src2 = 'sites/default/files/' . $_SESSION['ship image2'];
    return '<div class="col-sm-6 ship_1"> <img typeof="foaf:Image" src=' . $src1 . ' width="354" height="500"></div>' .
           '<div class="col-sm-6 ship_2"> <img typeof="foaf:Image" src=' . $src2 . ' width="354" height="500"></div>';
}
