<?php

function compare_ships_menu() {
    $items['compare_ships'] = array(
        'title' => 'Compare Ships',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('compare_ships_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

function compare_ships_form() {
    $form['ship1'] = array(
        '#title' => 'Ship 1',
        '#type' => 'select',
        '#description' => 'please choose a ship to compare',
        '#options' => $shipChoices = array(t('--- SELECT ---'), t('X-Wing'), t('A-Wing'), t('B-Wing')),
    );
    $form['ship2'] = array(
        '#title' => 'Ship 2',
        '#type' => 'select',
        '#description' => 'please choose a ship to compare',
        '#options' => $shipChoices = array(t('--- SELECT ---'), t('Tie-Fighter'), t('Tie Bomber'), t('Tie-Defender')),
    );
    return $form;
}
