<?php

function user_collection_menu() {
    $items['user_collection'] = array(
        'title' => 'User Collection',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('add_to_collection_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['add_to_collection_success_page'] = array(
        'title' => 'ship added',
        'page callback' => 'add_to_collection_success_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function add_to_collection_form() {
    $form['user_collection'] = array(
    '#title' => 'Which sets do you own?',
    '#type' => 'checkboxes',
    '#options' => array('Core Set' => ('Core Set'),'Force Awakens Core Set' => ('Force Awakens Core Set'),'X-wing' => ('X-wing')),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Add!',
        '#submit' => array('add_to_collection_form_submit'),
    );
    return $form;
}

function add_to_collection_form_submit($form, &$form_state) {
    $collection = $form_state['values']['user_collection'];

    // echo '<pre>';
    // print_r($collection);
    // print_r(implode(', ',$collection));
    // echo '</pre>';
    // exit;

    $_SESSION['collection'] = $collection;

    $form_state['redirect'] = 'add_to_collection_success_page';
}

function add_to_collection_success_page() {
    $final = $_SESSION['collection'];

    echo '<pre>';
    print_r($final);
    echo '</pre>';
    exit;

    return $final;
}
