<?php

function group_collection_menu() {
    $items['group_collection'] = array(
        'title' => 'Group collection',
        'page callback' => 'group_collection',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}

// function group_collection() {
//     return "hi";
// }



function group_collection($entry = array()) {
    $group_collection = array();

    $query = db_select('field_revision_field_collection', 'field_collection_value');
    $query->fields('field_collection_value');
    $result = $query->execute();
    while($record = $result->fetchAssoc())
      array_push($group_collection, $record);

    $final_collection = array();
    $final_owners = array();
    echo '<pre>';

    foreach($group_collection as $item => $name) {
        // $final_collection[$item['field_collection_value']];
        array_push($final_collection, $item);
        array_push($final_owners, $item['entity_id']);
        // print_r($item['entity_id']);
            // print_r(array_search($item['field_collection_value']);
            // $final_collection[$location] += [$item['entity_id']];

        // print_r($item['field_collection_value']);
        // print_r($item['entity_id']);
    }

    print_r($final_collection); //display array unique
    print_r($final_owners);
    echo '</pre>';
    exit;

}
